# Generated by Django 2.1 on 2018-10-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_portfolio', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Object',
        ),
    ]
