# Generated by Django 2.1 on 2018-10-08 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('the_portfolio', '0003_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_discription',
            new_name='project_description',
        ),
    ]
