# Generated by Django 2.1 on 2018-10-28 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_portfolio', '0006_auto_20181009_1354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='project',
            name='repo_url',
            field=models.URLField(default='https://github.com/abodftw'),
        ),
    ]
